import { ClerkProvider, ClerkLoaded, ClerkLoading } from '@clerk/nextjs';


import Header from "@/components/Header";
import "./globals.css";
import Loader from '@/components/Loader';


export const metadata = {
  title: "Auth app",
  description: "Generated by create Next js",
};

export default function RootLayout({ children }) {
  return (
   <ClerkProvider>
     <html lang="en">
      <body>

        <ClerkLoading>
            <Loader/>
        </ClerkLoading>
        
        <ClerkLoaded>
            <Header />
            {children}
        </ClerkLoaded>
      </body>
    </html>
   </ClerkProvider>
  );
}
